#pragma once
#include "Kernel.h"

#ifndef VGA13 

#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN 0x02
#define FOREGROUND_CYAN 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_LIGHTGRAY 0x07
#define FOREGROUND_DARKGRAY 0x08
#define FOREGROUND_LIGHTBLUE 0x09
#define FOREGROUND_LIGHTGREEN 0x0A
#define FOREGROUND_LIGHTCYAN 0x0B
#define FOREGROUND_LIGHTRED 0x0C
#define FOREGROUND_LIGHTMAGENTA 0x0D
#define FOREGROUND_YELLOW 0x0E
#define FOREGROUND_WHITE 0x0F

#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LIGHTGRAY 0x70
#define BACKGROUND_LIGHTBLACK 0x80
#define BACKGROUND_LIGHTBLUE 0x90
#define BACKGROUND_LIGHTGREEN 0xA0
#define BACKGROUND_LIGHTCYAN 0xB0
#define BACKGROUND_LIGHTRED 0xC0
#define BACKGROUND_LIGHTMAGENTA 0xD0
#define BACKGROUND_LIGHTYELLOW 0xE0
#define BACKGROUND_LIGHTWHITE 0xF0

#else 
#define FOREGROUND_BLACK 0x0
#define BACKGROUND_BLACK 0x0

#define FOREGROUND_BLUE 0x1
#define BACKGROUND_BLUE 0x1

#define FOREGROUND_GREEN 0x2
#define BACKGROUND_GREEN 0x2

#define FORGEOUND_CYAN 0x3
#define BACKGROUND_CYAN 0x3

#define FOREGROUND_RED 0x4
#define BACKGROUND_RED 0x4

#define FOREGROUND_MAGENTA 0x5
#define BACKGROUND_MAGENTA 0x5

#define FOREGROUND_BROWN 0x6
#define BACKGROUND_BROWN 0x6

#define FOREGROUND_LIGHTGRAY 0x7
#define BACKGROUND_LIGHTGRAY 0x7

#define FOREGROUND_WHITE 0xF
#define BACKGROUND_WHITE 0xF

#endif
